### ISSUE TITLE
Running simple.py

### ISSUE THREAD

**Issue by mgepner** [kunglab/ebnn#1]
After cloning the git repo and using setup.py build/ install, simply.py will not run. 
I get this error ->
eBNN/lib/python3.6/site-packages/hybrid-1-py3.6.egg/chainer_sequential/__init__.py", line 3, in <module>
ModuleNotFoundError: No module named 'util'

I am not sure why it is trying to access the .egg file as though it is a directory. Is there any assistance I can receive to get simple.py running?

**Comment by mgepner** [comment]
I fixed my issue I listed above, but I now have another issue. 

python simple.py 
Traceback (most recent call last):
  File "simple.py", line 8, in <module>
    from elaas.elaas import Collection
  File "build/bdist.linux-x86_64/egg/elaas/elaas.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/elaas/family/simple.py", line 1, in <module>
    import os
  File "build/bdist.linux-x86_64/egg/chainer_sequential/__init__.py", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/chainer_sequential/chain.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/chainer_sequential/sequential.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/chainer_sequential/binary_link.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/chainer_sequential/binary/links/__init__.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/chainer_sequential/binary/links/link_batch_normalization.py", line 3, in <module>
ImportError: cannot import name batch_normalization

Do you know why batch_normalization cannot be imported?

**Comment by BradMcDanel** [comment]
Sorry for just getting to this. It is due to a difference in the Chainer API from the version this was originally written with. I will be updating this today to fix it and will close this issue when it is done. There may be a few other issues in the codebase due to this as well that I will need to fix. Thanks.

**Comment by mgepner** [comment]
Thanks for the help

**Comment by mgepner** [comment]
Just a quick note, I also had to pip install cupy in order to get chainer to work properly. I am not sure if you needed that as well or if you wanted to make a note of that.

**Comment by BradMcDanel** [comment]
Yes -- the requirements.txt file needs to be updated to account for cupy and some other missing dependencies. I will update that as well. Thanks.

**Comment by BradMcDanel** [comment]
Please see the revised readme on how to install the requirements (virtualenv is not required, but I wrote it taking it into consideration). See if you can run [simple.py](https://github.com/kunglab/ebnn/blob/master/examples/simple.py) after that. 

I am working to verify that the generated header file output is still correct after all these modifications I made. Thanks.

**Comment by mgepner** [comment]
I have been able to run simple.py since yesterday, I believe not having cupy was the issue. Is there any advice you can give about making a network for my own data set?
EDIT: I haven't tried with your new push, I mean I got simple.py working with the older stuff.

**Comment by BradMcDanel** [comment]
Since you have it working, I will close this issue (and reach out in email).
