### ISSUE TITLE
cifar10 do not work with chainer-2.1

### ISSUE THREAD

**Issue by fabiovito** [kunglab/ebnn#3]
cifar10 do not work with chainer-2.1. mnist works.

python simple.py --verbose --dataset cifar10

Traceback (most recent call last):
  File "simple.py", line 15, in <module>
    util.train_model(model, train, test, args)
  File "/home/fabio/cnn/ebnn/ebnn/examples/util.py", line 50, in train_model
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 296, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 528, in update
    loss = lossfun(*args, **kwds)
  File "/home/fabio/cnn/ebnn/ebnn/examples/net.py", line 26, in __call__
    h = self.l1(x)
  File "/home/fabio/cnn/ebnn/ebnn/ebnn/links/link_conv_pool_BN_BST.py", line 29, in __call__
    h = self.bconv(h)
  File "/home/fabio/cnn/ebnn/ebnn/ebnn/links/link_binary_convolution.py", line 57, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/home/fabio/cnn/ebnn/ebnn/ebnn/functions/function_binary_convolution_2d.py", line 306, in binary_convolution_2d
    return func(x, W, b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 188, in __call__
    self._check_data_type_forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 292, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/home/fabio/cnn/ebnn/ebnn/ebnn/functions/function_binary_convolution_2d.py", line 49, in check_type_forward
    x_type.shape[1] == w_type.shape[1],
  File "/usr/local/lib/python2.7/dist-packages/chainer/utils/type_check.py", line 514, in expect
    expr.expect()
  File "/usr/local/lib/python2.7/dist-packages/chainer/utils/type_check.py", line 472, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
chainer.utils.type_check.InvalidType: 
Invalid operation is performed in: BinaryConvolution2DFunction (Forward)

Expect: in_types[0].shape[1] == in_types[1].shape[1]
Actual: 3 != 1

pip show chainer

Name: chainer
Version: 2.1.0
Summary: A flexible framework of neural networks
Home-page: http://chainer.org/
Author: Seiya Tokui
Author-email: tokui@preferred.jp
License: MIT License
Location: /usr/local/lib/python2.7/dist-packages
Requires: filelock, mock, nose, numpy, protobuf, six, cupy

**Comment by BradMcDanel** [comment]
Thanks for raising the issue. Please reopen if you still encounter problems. The accuracy of CIFAR-10 using this really small network can probably only achieve ~40-50%.
