### ISSUE TITLE
module 'cupy.cudnn' has no attribute 'cudnn'

### ISSUE THREAD

**Issue by Carreraa** [kunglab/ebnn#9]
Hello Brad

when I tried to run alex.py, I run into this 'AttributeError:module 'cupy.cudnn' has no attribute 'cudnn''

The detail is as following:

/usr/bin/python3.5 /home/carrera/WebAR/ebnn/examples/alex.py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/carrera/WebAR/ebnn/examples/alex.py", line 4, in <module>
    import net
  File "/home/carrera/WebAR/ebnn/examples/net.py", line 10, in <module>
    import ebnn.links as BL
  File "/home/carrera/WebAR/ebnn/ebnn/links/__init__.py", line 77, in <module>
    from .link_binary_convolution import BinaryConvolution2D
  File "/home/carrera/WebAR/ebnn/ebnn/links/link_binary_convolution.py", line 12, in <module>
    from ..functions.function_binary_convolution_2d import binary_convolution_2d
  File "/home/carrera/WebAR/ebnn/ebnn/functions/function_binary_convolution_2d.py", line 11, in <module>
    libcudnn = cuda.cudnn.cudnn
AttributeError: module 'cupy.cudnn' has no attribute 'cudnn'

This is my environment :  pycharm , chainer4.2.0 , cupy4.2.0 , cuda9.0 , cudnn7.0.5 

Do you know how to solve this problem?

Thank you
Carrera

**Comment by BradMcDanel** [comment]
Most likely it is a version difference in Chainer. This code was written using Chainer v2. If it fails to run on v2, then please post a followup. Thanks!

**Comment by Carreraa** [comment]
Me again

I setup all packages listed in the requirements.txt in my virtualenv, but I run into this problem as following:

/usr/bin/python3.5 /home/carrera/WebAR/ebnn/examples/alex.py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/carrera/WebAR/ebnn/examples/alex.py", line 20, in <module>
    util.train_model(model, train, test, args)
  File "/home/carrera/WebAR/ebnn/examples/util.py", line 32, in train_model
    cuda.get_device(args.gpu).use()
  File "/usr/local/lib/python3.5/dist-packages/chainer/backends/cuda.py", line 223, in get_device
    return _get_device(*args)
  File "/usr/local/lib/python3.5/dist-packages/chainer/backends/cuda.py", line 229, in _get_device
    check_cuda_available()
  File "/usr/local/lib/python3.5/dist-packages/chainer/backends/cuda.py", line 90, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module named 'cupy'

Is this because cupy1.0.1 is not compatible with cuda9.0 or other problems ？

Thanks

**Comment by BradMcDanel** [comment]
I am not sure -- but it very well could be due to cuda9.0. I realize it can be a pain to get things setup correctly, especially for older versions. If I ever get time I may upgrade this to chainer 4, but it is always a constant maintenance issue of keeping projects up to date.

**Comment by MohanadOdema** [comment]
Hello,

Indeed for me the problem was due to the difference in Chainer versions. Under different versions, the hierarchy of the imported modules in Chainer can be a bit different plus some of the methods may have alternate names in the newer versions. I followed it through and got it working on my GPU.

Regarding the file function_binary_convolution_2d.py above, it worked for me by changing the declaration in line 11 from
 `libcudnn = cuda.cudnn.cudnn` to `libcudnn = cuda.cupy.cuda.cudnn`

I also used the help function on the imported module `cuda.cupy.cuda.cudnn` to get the new names of the methods need in this file.  

I used for my environment chainer==6.3.0 and cupy-cuda101==6.3.0. My cuda toolkit is 10.0.1.

I'am attaching this modified file for references.
[function_binary_convolution_2d.txt](https://github.com/kunglab/ebnn/files/4843213/function_binary_convolution_2d.txt)
